configfile: "config/config.yaml"

#Final output files

#rule all: 
#	input:


#RULES

include: "rules/Preprocess.smk"
include: "rules/Collectreadcounts.smk"
include: "rules/Denoisereadcounts.smk"
include: "rules/Collectalleliccounts.smk"
include: "rules/Modelandcall.smk"

