fasta: "data/reference/hs38DH.fa"
intervals: "data/reference/Aurora_US.Exome_2019.bed"
normal_bam_dir: "data/bams/normal/"
tumor_bam_dir: "data/bams/tumor/"

#specify parameters for preprocess interval list 
seq_type: "WES"
bin_length: "1000"
padding: "250"
java_opts: "-Xmx4g" #preprocess intervals

#specify max memory for other rules
java_opts_allelic: "-Xmx15g" #allelic counts
java_opts_denoise: "-Xmx12g" #denoise read counts 
java_opts_model: "-Xmx31g" #model segments 

#specify your samples here
#tumor_samples and normal pair
pairs:
  "AUR-AG12-TTM1": "AUR-AG12-NB1"
 # "AUR-AG12-TTP1": "AUR-AG12-NB1"

#specify to run JSON
sample_name: AUR-AG12-TTM1
case_name: AUR-AG12
sample_type: Tumor_Normal
